excluded:
  - Resources
  - UI
  
disabled_rules:
  - opening_brace
  - unused_closure_parameter
  - operator_whitespace

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - fatal_error_message
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_function_chains
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_set_access_control
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unavailable_function
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call

  ### Rule modifications

identifier_name:
  min_length: 2
  max_length:
    warning: 80
    error: 120
  allowed_symbols: 
    - "_"
    - "."
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z
    - w
    - P3
  validates_start_with_lowercase: false

line_length:
  warning: 180
  error: 220
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 800
  error: 1000

file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 15
  error: 25

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_comments: true
  ignores_empty_lines: true

modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

excluded:
  - Resources
